### ISSUE TITLE
Add ability to filter CloudFormation Status

### ISSUE THREAD

**Issue by Skarlso** [devops-israel/aws-inventory#4]
"Would be nice" feature. I have no front-end skills, so I have no idea how hard this would be to add to a static page. Maybe some css magic?

Basically, now every status outcome is listed, like `DELETE_COMPLETE` as well. Would be awesome to be able to filter things like `CREATE_COMPLETE` or such nonsense.

This might not be that easy, since the output could be rather filtered through parameters for example. So you might add a service called `Running CF Stacks` and `Deleted CF Stacks` which might be easier to achieve rather than hacking the front-end. I'll leave that up to you. :)

**Comment by kesor** [comment]
Can probably be implemented using JMESPath Filter Expressions, http://jmespath.readthedocs.io/en/latest/proposals/filter-expressions.html

I did approach the CloudFormation team to take a look at this, since according to https://forums.aws.amazon.com/thread.jspa?threadID=87447 these stacks should be purged.

**Comment by kesor** [comment]
@Skarlso I loved the idea to separate the stacks!
Implemented in https://github.com/devops-israel/aws-inventory/commit/40dc4d7e5c1cc0f34e67deaecdd9f61fa159d5fc

**Comment by Skarlso** [comment]
Cool!! :) Awesome stuff, thanks! :)
